[package]
name = "rust"
version = "0.1.0"
authors = ["Thomas Schönauer <t.schoenauer@hgs-wt.at>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
